sli/databrowser/config/routes.rb
DbRails::Application.routes.draw do
  get "schools/index"

  get "teachers/index"

  get "students/index"

  
  root :to => 'entities#index', :defaults => {:type => "home"}
  match '/entities/:type' => 'entities#index'
  match '/entities/*other' => 'entities#show'

  
  match '/students' => 'students#index'
  match '/teachers' => 'teachers#index'
  match '/schools' => 'schools#index'
  match '/logout' => 'checks#logout'  

  

end

sli/databrowser/app/models/entity.rb
class Entity < SessionResource
  self.site = APP_CONFIG['api_base']
  
  def self.get_simple_and_complex(parameters)
    base = get(parameters)
    entity = []
    if base.is_a?(Array) and !base.empty?
      type = nil
      return entity if base.first.nil?
      type = VIEW_CONFIG[base.first['entityType']] if base.first.has_key? 'entityType'
      base.each do |single|
        one = Hash.new
        one[:simple] = build_simple_hash(type, single)
        one[:complex] = single
        entity.push(one)
      end
    else
      entity.push({:complex => base, :simple => nil})
    end
    entity
  end
  
  def self.build_simple_hash(type, hash)
    return nil if hash.nil?
    type = get_basic_types(hash) if type.nil?
    one = {}
    type.each do |item|
      final_type = item.split('/').last
      one[final_type] = value_for_simple_view(item, hash)
    end
    one
  end
  
  def self.value_for_simple_view (type, hash)
    return nil if hash.nil? or type.nil?
    return hash[type] unless type.include? '/'
    temp_hash = hash
    type_split = type.split '/'
    type_split.each do |split|
      if temp_hash.is_a?(Array)
        temp_hash = temp_hash.first[split]
      elsif temp_hash.has_key? split
        temp_hash = temp_hash[split]
      else
        return nil
      end
    end
    temp_hash
  end
  
  def self.get_basic_types(hash)
    types = []
    hash.keys.each do |key|
      if !hash[key].is_a?(Hash) and !hash[key].is_a?(Array) and key != 'entityType'
        types.push(key)
      end
    end
    types.slice(0, 5)
  end
end

sli/databrowser/app/controllers/entities_controller.rb
require "active_resource/base"

class EntitiesController < ApplicationController
  before_filter :set_params, :set_url
  skip_before_filter :set_params, :only => [:index]  
  
  def set_params
    split_path = params[:other].split('/')
    redirect_to "entities/#{split_path.first}" if split_path.size == 1
    id_index = split_path.index {|path| /[0-9]/ =~ path}
    params[:type] = split_path.slice(0...id_index).join('/')
    params[:id] = split_path.slice(id_index...split_path.size).join('/')
  end
  
  def set_url
      Entity.url_type = params[:type]
      case params[:type]
      when /association/
        logger.debug {"Full json support on"}
        Entity.format = ActiveResource::Formats::JsonFullFormat
      else
        logger.debug {"Full json support off"}
        Entity.format = ActiveResource::Formats::JsonFormat
      end
    end
  
  # rescue_from ActiveResource::ResourceNotFound do |exception|
  #   render :file => "404.html"
  # end
  
  
  # GET /entities
  # GET /entities.json
  def index
    Entity.url_type = params[:type]
    @entities = Entity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entities }
    end
  end

  # GET /entities/1
  # GET /entities/1.json
  def show
    @entity = Entity.get_simple_and_complex(params[:id])
    # @entity = Entity.find(:all, :from => "/api/rest/#{params[:other]}")
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entity }
    end
  end
  
  # GET /entities/new
  # GET /entities/new.json
  # def new
  #   @entity = Entity.new
  # 
  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.json { render json: @entity }
  #   end
  # end
  # 
  # # GET /entities/1/edit
  # def edit
  #   @entity = Entity.find(params[:id])
  # end

  # # POST /entities
  # # POST /entities.json
  # def create
  #   @entity = Entity.new(params[:entity])
  # 
  #   respond_to do |format|
  #     if @entity.save
  #       format.html { redirect_to @entity, notice: 'Entity was successfully created.' }
  #       format.json { render json: @entity, status: :created, location: @entity }
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @entity.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  # 
  # # PUT /entities/1
  # # PUT /entities/1.json
  # def update
  #   @entity = Entity.find(params[:id])
  # 
  #   respond_to do |format|
  #     if @entity.update_attributes(params[:entity])
  #       format.html { redirect_to @entity, notice: 'Entity was successfully updated.' }
  #       format.json { head :ok }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @entity.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  # 
  # # DELETE /entities/1
  # # DELETE /entities/1.json
  # def destroy
  #   @entity = Entity.find(params[:id])
  #   @entity.destroy
  # 
  #   respond_to do |format|
  #     format.html { redirect_to entities_url }
  #     format.json { head :ok }
  #   end
  # end
end

sli/databrowser/app/helpers/entities_helper.rb
module EntitiesHelper

  def localize_url(url)
    url.gsub( APP_CONFIG['api_base'], "http://#{request.host_with_port}/entities") unless url.nil?
  end
  
  def build_links(hash)
  	html = ""
  	if hash.is_a?(Array)
  		html << '<ul>'
  		hash.each do |link|
  			html << '<li>' << link_to( t(link["rel"]), localize_url(link["href"]) ) << '</li>'
  		end
  		html << '</ul>'
  	else
  		html << link_to( t(hash["rel"]), localize_url(hash["href"]) )
  	end
  	html
  end 

  def display_hash (hash = {}, indent = 0)
  	html = ""
  	return if hash.empty?
  	if indent != 0
  		html << "<dl>"
  	end
  	hash.each do |key, value|
  		case key
  		when 'links', 'link'
  			html << "<dt><b>#{t(key)}:</b></dt>"
  			html << "<dd>#{build_links value}</dd>"
  		when 'id'
  			# do not print id
  		else
  			html << "<dt><b>#{t(key)}:</b></dt>"
  			html << "<dd>"
  			if value.is_a?(Hash)
  				display_hash(value, indent+1)
  			elsif value.is_a?(Array)
  				value.each do |item| 
  					if item.is_a? Hash
  						html << display_hash(item, indent+1)
  					else
  						html << value.join(', ')
  						break
  					end
  				end
  			else
  				html << value.to_s
  			end
  			html << "</dd>"
  		end	
  	end
  	if indent != 0
  		html << "</dl>"
  	end
  	html
  end
  
end

sli/databrowser/app/views/entities/_detail.html.erb
<%=
html = ""
if entity[:complex].empty?
	html << "Entity is empty"
else
	html << display_hash(entity[:complex])
end
html.html_safe
%>

sli/databrowser/app/views/entities/_form.html.erb
<%= form_for(@entity) do |f| %>
  <% if @entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
      <% @entity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sli/databrowser/app/views/entities/_simple.html.erb
<%= javascript_include_tag :jExpand %>
<table id="simple">
	<tr>
		<% entity.first[:simple].keys.each do |header| %>
			<th><%= t(header) %></th>
		<%end%>
	</tr>
	<% entity.each do |entity| %>
	<% single = entity[:simple] %>
		<tr>
		<% single.each do |keys, value| %>
			<td><%= value %>
		<% end %>
		</tr>
		<tr >
			<td colspan=<%= "#{single.keys.size}" %>> <%= render :partial => "detail", :locals => {:entity => entity}%></td>
		</tr>
	<%end%>
</table>

<script type="text/javascript" charset="utf-8">
	jQuery(document).ready(function() {
		jQuery.noConflict();
		// jQuery('#simple').jExpand();
		jQuery("#simple tr:odd").addClass("odd");
		        jQuery("#simple tr:not(.odd)").hide();
		        jQuery("#simple tr:first-child").show();
		        
		        jQuery("#simple tr.odd").click(function(){
		            jQuery(this).next("tr").slideToggle();
		            // $(this).find(".arrow").toggleClass("up");
		        });
	});
</script>

sli/databrowser/app/views/entities/edit.html.erb
<h1>Editing entity</h1>

<%= render 'form' %>

<%= link_to 'Show', @entity %> |
<%= link_to 'Back', entities_path %>

sli/databrowser/app/views/entities/index.html.erb
<div id='data'>
<h1>Listing Home </h1>
<% @entities.each do |entity| %>
	<p><%= link_to t(entity.rel), localize_url(entity.href) %></p>
<% end %>
</div>

sli/databrowser/app/views/entities/new.html.erb
<h1>New entity</h1>

<%= render 'form' %>

<%= link_to 'Back', entities_path %>

sli/databrowser/app/views/entities/show.html.erb
<h2>Viewing information for <%= t(params[:type].split('-').join(' '))%> with ID: <%= params[:id]%></h2>
<p><%= link_to 'Back', :back %></p>
<% if @entity.size == 1 %>
	<%= render :partial => "detail", :locals => {:entity => @entity.first} %>
<%else%>
	<%= render :partial => "simple", :locals => {:entity => @entity} %>
<% end %>