sli/admin-tools/admin-rails/config/routes.rb
SLIAdmin::Application.routes.draw do
  get "sessions/new"

  

    resources :roles
    resources :sessions

    resources :realms do
      member do
        put :update
      end
    end
    
    match '/logout', :to => 'sessions#destroy'
    match '/callback', :to => 'application#callback'
	

  root :to => 'roles#index'

end

sli/admin-tools/admin-rails/app/models/role.rb
class Role < SessionResource
  self.site = "#{APP_CONFIG['api_base']}/admin/"
  
  def self.get_static_information
    @roles = Role.all
    @roles.each do |role|
      role.examples = nil
      role.individual = nil
      case role.name
      when /Aggregator/
        role.examples = "State Data Analyst, State DOE Representative"
        role.individual = nil
      when /Leader/
        role.examples = "School Principal, District Superintendent, State Superintendent" 
        role.individual = "student enrolled in my district(s) or school(s)"
      when /Educator/
        role.examples = "Teacher, Athletic Coach, Classroom Assistant"
        role.individual = "student enrolled in my sections"
      when /IT Administrator/
        role.examples = "SLC Operator, SEA IT Admin, LEA IT Admin"
        role.individual = "student enrolled in my district(s) or school(s)"
      end
      role.general = []
      role.restricted = []
      role.aggregate = nil
      role.rights.each do |right|
        case right
        when /AGGREGATE_READ/
          role.aggregate = "yes"
        when /READ_GENERAL/
          role.general << "R"
        when /READ_RESTRICTED/
          role.restricted << "R"
        when /WRITE_GENERAL/
          role.general << "W"
        when /WRITE_RESTRICTED/
          role.restricted << "W"
        end    
      end
      role.general = role.general.join('/')
      role.restricted = role.restricted.join('/')
    end
    @roles
  end
end

sli/admin-tools/admin-rails/app/controllers/roles_controller.rb
include ActiveSupport::Rescuable

class RolesController < ApplicationController

  rescue_from ActiveResource::ForbiddenAccess, :with => :render_403
  rescue_from ActiveResource::ResourceNotFound, :with => :render_404

  # GET /roles
  # GET /roles.json
  def index
   @roles = Role.get_static_information
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])
  
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # # GET /roles/new
  # # GET /roles/new.json
  # def new
  #   @role = Role.new
  # 
  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.json { render json: @role }
  #   end
  # end

  # GET /roles/1/edit
  # def edit
  #   @role = Role.find(params[:id])
  # end

  # POST /roles
  # POST /roles.json
  # def create
  #   @role = Role.new(params[:role])
  # 
  #   respond_to do |format|
  #     if @role.save
  #       format.html { redirect_to @role, notice: 'Role was successfully created.' }
  #       format.json { render json: @role, status: :created, location: @role }
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @role.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PUT /roles/1
  # PUT /roles/1.json
  # def update
  #   @role = Role.find(params[:id])
  #   puts "Role found (Update): #{@role.attributes}"
  #   respond_to do |format|
  #     if @role.update_attributes(params[:role])
  #       format.html { redirect_to @role.id, notice: 'Role was successfully updated.' }
  #       format.json { head :ok }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @role.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /roles/1
  # DELETE /roles/1.json
  # def destroy
  #   @role = Role.find(params[:id])
  #   @role.destroy
  # 
  #   respond_to do |format|
  #     format.html { redirect_to roles_url }
  #     format.json { head :ok }
  #   end
  # end
end

sli/admin-tools/admin-rails/app/helpers/roles_helper.rb
module RolesHelper
end

sli/admin-tools/admin-rails/app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
<% if @role.errors.any? %>
<div id    = "error_explanation">
	<h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

	<ul>
		<% @role.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class = "actions">
	<%= f.submit "Submit", :disable_with => 'Submiting...' %>
</div>
<% end %>

sli/admin-tools/admin-rails/app/views/roles/edit.html.erb
<h1>Editing role</h1>
<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

<script type="text/javascript">

</script>

sli/admin-tools/admin-rails/app/views/roles/index.html.erb
<h1>Default SLI Roles</h1>

<table>
  <tr>
    <th>SLI Role</th>
    <th>Examples</th>
    <th>Aggregate</th>
    <th>Individual Record Data</th>
	<th>General Student Data</th>
	<th>Restricted Student Data</th>
	<th>Actions</th>
  </tr>

<% @roles.each do |role| %>
  <tr>
    <td><%= role.name %></td>
    <td><%= role.examples %></td>
	<td><%= role.aggregate %></td>
	<td><%= role.individual %></td>
	<td><%= role.general %></td>
	<td><%= role.restricted %></td>
  </tr>
<% end %>
</table>

<br />

sli/admin-tools/admin-rails/app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

sli/admin-tools/admin-rails/app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @role.name %>
</p>


<%= link_to 'Edit', edit_role_path(@role.id) %> |
<%= link_to 'Back', roles_path %>