sli/admin-tools/admin-rails/config/routes.rb
SLIAdmin::Application.routes.draw do
  get "sessions/new"

  

    resources :roles
    resources :sessions

    resources :realms do
      member do
        put :update
      end
    end
    
    match '/logout', :to => 'sessions#destroy'
    match '/callback', :to => 'application#callback'
	

  root :to => 'roles#index'

end

sli/admin-tools/admin-rails/app/models/realm.rb
class Realm < SessionResource

  self.site = "#{APP_CONFIG['api_base']}"
  self.collection_name = "realm"

end

sli/admin-tools/admin-rails/app/controllers/realms_controller.rb
include ActiveSupport::Rescuable

class RealmsController < ApplicationController

  rescue_from ActiveResource::ForbiddenAccess, :with => :render_403
  rescue_from ActiveResource::ResourceNotFound, :with => :render_404

  # GET /realms
  # GET /realms.json
  def index
    #figure out the realm this user has access to
    userRealm = get_user_realm
    realmToRedirectTo = nil
    realms = Realm.all
    realms.each do |realm|
      realmToRedirectTo = realm if realm.idp.id == userRealm
    end
    if realmToRedirectTo != nil
      redirect_to realmToRedirectTo
      return
    end
    render_404
  end

  # # GET /realms/1
  # # GET /realms/1.json
   def show
     @realm = Realm.find(params[:id])
     respond_to do |format|
       format.html # show.html.erb
       format.json { render json: @realm }
     end
   end

  # # GET /realms/1/edit
   def edit
     @realm = Realm.find(params[:id])
     @sli_roles = get_roles
   end

  # # PUT /realms/1
   def update
     @realm = Realm.find(params[:id])

     @realm.mappings = params[:mappings];
     respond_to do |format|
       success = false
       errorMsg = ""

       begin
         success =  @realm.save()
       rescue ActiveResource::BadRequest => error
         errorMsg = error.response.body
       end

       if success && params[:mappings] != nil
         format.json { render json: @realm }
       else
         format.json { render json: errorMsg, status: :unprocessable_entity }
       end
	
     end
   end

private

  # Uses the /role api to get the list of roles
  def get_roles()
    roles = Role.all
    toReturn = []
    roles.each do |role|
      toReturn.push role.name unless role.name == "SLI Administrator"
    end
    toReturn
  end

  #TODO:  current we're just checking the realm the user authenticated to,
  # but ultimately we need to get that somewhere else since the user will
  # always be authenticated to the SLI realm
  def get_user_realm
    return Check.new(SessionResource.auth_id).realm
  end

end

sli/admin-tools/admin-rails/app/helpers/realms_helper.rb
module RealmsHelper
end

sli/admin-tools/admin-rails/app/views/realms/edit.html.erb
  <h2>Editing role mappings for <%=@realm.state%></h2>

  <script type="text/javascript">

  //initial data for table
  var rMap = getTableData(<%= @realm.mappings.to_json.html_safe %>);

  //intial sorting -- 1 == desc, -1 = asc
  var sortOrder = [1,1];

  //which column to sort by 
  var sortCol = 0; 

  sortTable(rMap, sortCol, sortOrder[sortCol]);
  var SLI_ROLES = <%= @sli_roles.to_json.html_safe %>;
  var UPDATE_URL = '<%= url_for(:action=>"update") %>'

  $(document).ready(function() {
    initRealmEdit();
  });

  </script>

  <table>
    <tr>

      <td valign="top">
        <% @sli_roles.each do |role| %>

        <div>
          <%= radio_button_tag 'role', role %><%= label_tag "role_#{role}", role %>
        </div><% end %>
      </td>

      <td valign="top">
      <%= label_tag "clientRole", "Client role" %><input id=
      "clientRole"></td>

      <td valign="top"><button id="addButton">Add</button></td>
    </tr>
  </table>

  <table>
    <thead>
      <tr>
        <th id="cRole" style="text-decoration: underline">Client
        role
        <span><%= image_tag "sort_asc.png", :class => 'sort_asc', :style => 'display: none' %>
        <%= image_tag "sort_desc.png", :class => 'sort_desc' %></span></th>

        <th id="sRole" style="text-decoration: underline">SLI role
        <span><%= image_tag "sort_asc.png", :class => 'sort_asc', :style => 'display: none' %>
        <%= image_tag "sort_desc.png", :class => 'sort_desc', :style => 'display: none' %></span></th>
      </tr>
    </thead>

    <tbody id="mTable"></tbody>
  </table>

  <div>
    <button id="resetButton">Reset to defaults</button>
  </div>

<%= link_to 'Back', realms_path %>

sli/admin-tools/admin-rails/app/views/realms/index.html.erb
<h1>Listing realms</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @realms.each do |realm| %>
	<tr>
    <td><%= realm.state %></td>
    <td><%= link_to 'Show', realm %></td>
    <td><%= link_to 'Edit', edit_realm_path(realm) %></td>
	</tr>
<% end %>

sli/admin-tools/admin-rails/app/views/realms/new.html.erb
<h1>New realm</h1>

<%= render 'form' %>

<%= link_to 'Back', realms_path %>

sli/admin-tools/admin-rails/app/views/realms/show.html.erb
<script>
//	var roles = <%= Role.all.to_json.html_safe %>
var rMap = getTableData(<%= @realm.mappings.to_json.html_safe %>);

$(document).ready(function() {
	drawTable(rMap, false);
});

</script>
<h2>Role mappings for <%=@realm.state%></h2>
<table>
        <thead><tr><th id="crole" style="text-decoration: underline">Client Role</th><th id="srole" style="text-decoration: underline">SLI Role</th></tr></thead>
        <tbody id="mTable"></tbody>
</table>

<%= link_to 'Edit', edit_realm_path(@realm) %>
<!--
don't need this since they'll just get redirected back here
<%= link_to 'Back', realms_path %>
-->